const GET_MUSICS = 'GET_MUSICS';
const GET_MUSICS_SUCCESS = 'GET_MUSICS_SUCCESS';
const GET_MUSICS_FAILURE = 'GET_MUSICS_FAILURE';
const SHOW_SELECTED_MUSIC = 'SHOW_SELECTED_MUSIC';

export { GET_MUSICS, GET_MUSICS_SUCCESS, GET_MUSICS_FAILURE, SHOW_SELECTED_MUSIC };